# Generated by Django 2.2.4 on 2019-10-26 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_auto_20190921_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Property',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='item',
            new_name='Property',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='item_img',
            new_name='Property_img',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='item',
            new_name='Property',
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='realestate.Address'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
